//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLXI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLXI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant modification.
        /// </summary>
        internal static string ConstantModificationException {
            get {
                return ResourceManager.GetString("ConstantModificationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division by zero.
        /// </summary>
        internal static string DivisionByZeroException {
            get {
                return ResourceManager.GetString("DivisionByZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal runtime error.
        /// </summary>
        internal static string InternalRuntimeError {
            get {
                return ResourceManager.GetString("InternalRuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nihil ex nihil.
        /// </summary>
        internal static string NilModificationException {
            get {
                return ResourceManager.GetString("NilModificationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a bignum.
        /// </summary>
        internal static string NotBignumException {
            get {
                return ResourceManager.GetString("NotBignumException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a character.
        /// </summary>
        internal static string NotCharException {
            get {
                return ResourceManager.GetString("NotCharException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a cons.
        /// </summary>
        internal static string NotConsException {
            get {
                return ResourceManager.GetString("NotConsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a double.
        /// </summary>
        internal static string NotDoubleException {
            get {
                return ResourceManager.GetString("NotDoubleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a fixnum.
        /// </summary>
        internal static string NotFixnumException {
            get {
                return ResourceManager.GetString("NotFixnumException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a float.
        /// </summary>
        internal static string NotFloatException {
            get {
                return ResourceManager.GetString("NotFloatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a floating point.
        /// </summary>
        internal static string NotFloatingPointException {
            get {
                return ResourceManager.GetString("NotFloatingPointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not an integer.
        /// </summary>
        internal static string NotIntegerException {
            get {
                return ResourceManager.GetString("NotIntegerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a list.
        /// </summary>
        internal static string NotListException {
            get {
                return ResourceManager.GetString("NotListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a number.
        /// </summary>
        internal static string NotNumberException {
            get {
                return ResourceManager.GetString("NotNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a rational number.
        /// </summary>
        internal static string NotRationalException {
            get {
                return ResourceManager.GetString("NotRationalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a sequence.
        /// </summary>
        internal static string NotSequenceException {
            get {
                return ResourceManager.GetString("NotSequenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a string.
        /// </summary>
        internal static string NotStringException {
            get {
                return ResourceManager.GetString("NotStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a symbol.
        /// </summary>
        internal static string NotSymbolException {
            get {
                return ResourceManager.GetString("NotSymbolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a vector.
        /// </summary>
        internal static string NotVectorException {
            get {
                return ResourceManager.GetString("NotVectorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range.
        /// </summary>
        internal static string RangeConstraintException {
            get {
                return ResourceManager.GetString("RangeConstraintException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol is unbound.
        /// </summary>
        internal static string SymbolUnboundException {
            get {
                return ResourceManager.GetString("SymbolUnboundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritas aeterna.
        /// </summary>
        internal static string TModificationException {
            get {
                return ResourceManager.GetString("TModificationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply declaration to undefined variable.
        /// </summary>
        internal static string UndefinedVariableDeclarationException {
            get {
                return ResourceManager.GetString("UndefinedVariableDeclarationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to redeclare variable.
        /// </summary>
        internal static string VariableRedeclarationException {
            get {
                return ResourceManager.GetString("VariableRedeclarationException", resourceCulture);
            }
        }
    }
}
